<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Electronics (category: electronics)
            [
                'name' => 'Apple iPhone 15 Pro',
                'slug' => 'apple-iphone-15-pro',
                'sku' => 'APP-IP15P-001',
                'description' => 'The latest iPhone with A17 Pro chip, titanium design, and a 48MP camera system. Features ProMotion 120Hz display and USB-C connectivity.',
                'price' => 999.99,
                'stock' => 45,
                'category' => 'electronics',
                'images' => ['https://images.unsplash.com/photo-1696446701796-da61225697cc?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Samsung 65" QLED 4K TV',
                'slug' => 'samsung-65-qled-4k-tv',
                'sku' => 'SAM-65Q4K-001',
                'description' => 'Stunning 65-inch QLED display with Quantum Dot technology, 4K resolution, and smart TV features powered by Tizen OS.',
                'price' => 1299.99,
                'stock' => 18,
                'category' => 'electronics',
                'images' => ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Sony WH-1000XM5 Headphones',
                'slug' => 'sony-wh-1000xm5-headphones',
                'sku' => 'SON-WH1000-001',
                'description' => 'Industry-leading noise canceling wireless headphones with 30-hour battery life and crystal clear hands-free calling.',
                'price' => 349.99,
                'stock' => 62,
                'category' => 'electronics',
                'images' => ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'MacBook Pro 14" M3',
                'slug' => 'macbook-pro-14-m3',
                'sku' => 'APP-MBP14-001',
                'description' => 'Apple MacBook Pro with M3 chip, 16GB RAM, 512GB SSD, Liquid Retina XDR display, and up to 18 hours battery life.',
                'price' => 1999.99,
                'stock' => 25,
                'category' => 'electronics',
                'images' => ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'iPad Air 5th Generation',
                'slug' => 'ipad-air-5th-generation',
                'sku' => 'APP-IPA5-001',
                'description' => '10.9-inch Liquid Retina display, M1 chip, 5G capable, USB-C connectivity, Touch ID, and available in five colors.',
                'price' => 749.99,
                'stock' => 38,
                'category' => 'electronics',
                'images' => ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Canon EOS R50 Camera',
                'slug' => 'canon-eos-r50-camera',
                'sku' => 'CAN-EOSR50-001',
                'description' => 'Compact mirrorless camera with 24.2MP APS-C sensor, 4K video recording, Dual Pixel CMOS AF II, and built-in Wi-Fi.',
                'price' => 679.99,
                'stock' => 20,
                'category' => 'electronics',
                'images' => ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Apple Watch Series 9',
                'slug' => 'apple-watch-series-9',
                'sku' => 'APP-AWS9-001',
                'description' => 'Smartwatch with S9 chip, always-on Retina display, blood oxygen monitoring, ECG app, and crash detection.',
                'price' => 399.99,
                'stock' => 54,
                'category' => 'electronics',
                'images' => ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Bose SoundLink Flex Speaker',
                'slug' => 'bose-soundlink-flex-speaker',
                'sku' => 'BOS-SLF-001',
                'description' => 'Portable Bluetooth speaker with waterproof design, 12-hour battery life, and PositionIQ technology for optimal sound anywhere.',
                'price' => 149.99,
                'stock' => 80,
                'category' => 'electronics',
                'images' => ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop'],
            ],
            // Clothing
            [
                'name' => "Levi's 501 Original Jeans",
                'slug' => 'levis-501-original-jeans',
                'sku' => 'LEV-501-001',
                'description' => "The original straight-leg jean with iconic button fly. Made from 100% cotton denim with a classic fit that never goes out of style.",
                'price' => 79.99,
                'stock' => 120,
                'category' => 'clothing',
                'images' => ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Nike Air Force 1 Sneakers',
                'slug' => 'nike-air-force-1-sneakers',
                'sku' => 'NIK-AF1-001',
                'description' => "Classic low-top basketball sneaker featuring genuine leather upper, Air-Sole unit for lightweight cushioning, and durable rubber outsole.",
                'price' => 110.00,
                'stock' => 95,
                'category' => 'clothing',
                'images' => ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'The North Face Puffer Jacket',
                'slug' => 'north-face-puffer-jacket',
                'sku' => 'TNF-PUF-001',
                'description' => '700-fill goose down insulation jacket with water-resistant DWR finish, secure zip pockets, and adjustable hood. Perfect for cold weather.',
                'price' => 229.99,
                'stock' => 40,
                'category' => 'clothing',
                'images' => ['https://images.unsplash.com/photo-1544923246-77307dd654cb?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Adidas Ultraboost 22 Running Shoes',
                'slug' => 'adidas-ultraboost-22-running-shoes',
                'sku' => 'ADI-UB22-001',
                'description' => 'High-performance running shoes with Boost midsole for energy return, Primeknit upper for adaptive fit, and Continental rubber outsole.',
                'price' => 189.99,
                'stock' => 70,
                'category' => 'clothing',
                'images' => ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Ralph Lauren Polo Shirt',
                'slug' => 'ralph-lauren-polo-shirt',
                'sku' => 'RAL-POL-001',
                'description' => 'Classic mesh polo shirt crafted from breathable cotton. Features signature embroidered pony, ribbed collar, and two-button placket.',
                'price' => 98.00,
                'stock' => 150,
                'category' => 'clothing',
                'images' => ['https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => "Women's Yoga Pants",
                'slug' => 'womens-yoga-pants',
                'sku' => 'WOM-YOG-001',
                'description' => 'High-waisted yoga pants made from moisture-wicking fabric with 4-way stretch. Features hidden waistband pocket and squat-proof design.',
                'price' => 54.99,
                'stock' => 200,
                'category' => 'clothing',
                'images' => ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Ray-Ban Aviator Sunglasses',
                'slug' => 'ray-ban-aviator-sunglasses',
                'sku' => 'RAY-AVI-001',
                'description' => 'Iconic aviator sunglasses with gold metal frame, G-15 crystal lenses providing 100% UV protection, and teardrop-shaped design.',
                'price' => 163.00,
                'stock' => 55,
                'category' => 'clothing',
                'images' => ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop'],
            ],
            // Home & Garden
            [
                'name' => 'Dyson V15 Detect Vacuum',
                'slug' => 'dyson-v15-detect-vacuum',
                'sku' => 'DYS-V15-001',
                'description' => 'Cordless vacuum with laser dust detection, HEPA filtration, 60-minute run time, and LCD screen showing real-time performance.',
                'price' => 749.99,
                'stock' => 22,
                'category' => 'home-garden',
                'images' => ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Instant Pot Duo 7-in-1',
                'slug' => 'instant-pot-duo-7-in-1',
                'sku' => 'INS-POT-001',
                'description' => '7-in-1 electric pressure cooker that functions as pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker, and warmer.',
                'price' => 89.95,
                'stock' => 75,
                'category' => 'home-garden',
                'images' => ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Philips Hue Smart Bulb Starter Kit',
                'slug' => 'philips-hue-smart-bulb-starter-kit',
                'sku' => 'PHI-HUE-001',
                'description' => 'Smart lighting starter kit with 3 A19 bulbs and Hue Bridge. Control with app or voice, set schedules, and choose from 16 million colors.',
                'price' => 129.99,
                'stock' => 60,
                'category' => 'home-garden',
                'images' => ['https://images.unsplash.com/photo-1586210579191-33b45e38fa2c?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'KitchenAid Stand Mixer',
                'slug' => 'kitchenaid-stand-mixer',
                'sku' => 'KIT-MIX-001',
                'description' => '5-quart tilt-head stand mixer with 10 speeds, 59 touch points around the bowl, and over 10 optional attachments available separately.',
                'price' => 379.99,
                'stock' => 30,
                'category' => 'home-garden',
                'images' => ['https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Nest Learning Thermostat',
                'slug' => 'nest-learning-thermostat',
                'sku' => 'NES-THM-001',
                'description' => 'Smart thermostat that learns your schedule and programs itself. Compatible with 95% of heating and cooling systems, saves energy automatically.',
                'price' => 249.99,
                'stock' => 42,
                'category' => 'home-garden',
                'images' => ['https://images.unsplash.com/photo-1545259742-46674f4a5938?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Wooden Coffee Table',
                'slug' => 'wooden-coffee-table',
                'sku' => 'WOD-CFT-001',
                'description' => 'Mid-century modern solid oak coffee table with tapered legs and lower shelf for extra storage. Dimensions: 47" W x 24" D x 18" H.',
                'price' => 299.00,
                'stock' => 15,
                'category' => 'home-garden',
                'images' => ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Monstera Deliciosa Plant',
                'slug' => 'monstera-deliciosa-plant',
                'sku' => 'MON-PLT-001',
                'description' => 'Popular tropical houseplant with iconic split leaves. Easy to care for, thrives in indirect light, and adds a lush, tropical vibe to any space.',
                'price' => 34.99,
                'stock' => 100,
                'category' => 'home-garden',
                'images' => ['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=600&auto=format&fit=crop'],
            ],
            // Books
            [
                'name' => 'Atomic Habits by James Clear',
                'slug' => 'atomic-habits-james-clear',
                'sku' => 'BOK-ATH-001',
                'description' => 'A proven framework for improving every day. Learn how tiny changes lead to remarkable results through the science of habit formation.',
                'price' => 18.99,
                'stock' => 200,
                'category' => 'books',
                'images' => ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'The Pragmatic Programmer',
                'slug' => 'the-pragmatic-programmer',
                'sku' => 'BOK-PRG-001',
                'description' => 'A guide for software developers covering coding philosophies, best practices, and career advice. Updated 20th anniversary edition.',
                'price' => 49.99,
                'stock' => 85,
                'category' => 'books',
                'images' => ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Sapiens by Yuval Noah Harari',
                'slug' => 'sapiens-yuval-noah-harari',
                'sku' => 'BOK-SAP-001',
                'description' => 'A brief history of humankind, exploring how Homo sapiens came to dominate Earth and shape human societies, cultures, and economies.',
                'price' => 17.99,
                'stock' => 175,
                'category' => 'books',
                'images' => ['https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Clean Code by Robert C. Martin',
                'slug' => 'clean-code-robert-martin',
                'sku' => 'BOK-CLN-001',
                'description' => 'Handbook of agile software craftsmanship. Packed with lessons on writing clean, maintainable code with real-world examples.',
                'price' => 44.99,
                'stock' => 90,
                'category' => 'books',
                'images' => ['https://images.unsplash.com/photo-1550399105-c4db5fb85c18?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'The Great Gatsby',
                'slug' => 'the-great-gatsby',
                'sku' => 'BOK-GAT-001',
                'description' => "F. Scott Fitzgerald's timeless classic exploring the American Dream, wealth, and social excess during the roaring 1920s.",
                'price' => 12.99,
                'stock' => 300,
                'category' => 'books',
                'images' => ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&auto=format&fit=crop'],
            ],
            // Sports
            [
                'name' => 'Peloton Bike+',
                'slug' => 'peloton-bike-plus',
                'sku' => 'SPT-PEL-001',
                'description' => 'Premium indoor cycling bike with 24" rotating HD touchscreen, auto-resistance with Apple Watch, and immersive live and on-demand classes.',
                'price' => 2495.00,
                'stock' => 10,
                'category' => 'sports',
                'images' => ['https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Wilson Pro Staff Tennis Racket',
                'slug' => 'wilson-pro-staff-tennis-racket',
                'sku' => 'SPT-WIL-001',
                'description' => 'Professional tennis racket with 97 sq inch head size, 16x19 string pattern, and RF97 Autograph design for precise control.',
                'price' => 239.99,
                'stock' => 35,
                'category' => 'sports',
                'images' => ['https://images.unsplash.com/photo-1617883861744-45a8e9c67ba8?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Hydro Flask 32oz Water Bottle',
                'slug' => 'hydro-flask-32oz-water-bottle',
                'sku' => 'SPT-HYD-001',
                'description' => 'Wide mouth insulated stainless steel water bottle that keeps drinks cold 24 hours and hot 12 hours. BPA-free with leak-proof lid.',
                'price' => 44.95,
                'stock' => 180,
                'category' => 'sports',
                'images' => ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Yoga Mat Premium',
                'slug' => 'yoga-mat-premium',
                'sku' => 'SPT-YOG-001',
                'description' => 'Non-slip, eco-friendly TPE yoga mat with alignment lines, 6mm thickness for joint support, and carrying strap included.',
                'price' => 64.99,
                'stock' => 130,
                'category' => 'sports',
                'images' => ['https://images.unsplash.com/photo-1601925228239-5f0e6b4bb388?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Bowflex SelectTech 552 Dumbbells',
                'slug' => 'bowflex-selecttech-552-dumbbells',
                'sku' => 'SPT-BOW-001',
                'description' => 'Adjustable dumbbells that replace 15 sets of weights. Dial system adjusts from 5 to 52.5 lbs in 2.5-lb increments.',
                'price' => 399.00,
                'stock' => 28,
                'category' => 'sports',
                'images' => ['https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop'],
            ],
            // Toys
            [
                'name' => 'LEGO Technic Bugatti Chiron',
                'slug' => 'lego-technic-bugatti-chiron',
                'sku' => 'TOY-LEG-001',
                'description' => 'Detailed 3,599-piece replica of the Bugatti Chiron with working 8-speed gearbox, moving pistons, and aerodynamic spoiler.',
                'price' => 349.99,
                'stock' => 22,
                'category' => 'toys',
                'images' => ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Nintendo Switch OLED',
                'slug' => 'nintendo-switch-oled',
                'sku' => 'TOY-NIN-001',
                'description' => 'Gaming console with vibrant 7-inch OLED screen, wide adjustable stand, enhanced audio, 64GB internal storage, and wired LAN port.',
                'price' => 349.99,
                'stock' => 48,
                'category' => 'toys',
                'images' => ['https://images.unsplash.com/photo-1585565804112-f201f68c48b4?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Barbie Dreamhouse',
                'slug' => 'barbie-dreamhouse',
                'sku' => 'TOY-BAR-001',
                'description' => '3-story dollhouse with 8 rooms, working elevator, pool with waterslide, and 70+ accessories. Lights and sounds included.',
                'price' => 199.99,
                'stock' => 30,
                'category' => 'toys',
                'images' => ['https://images.unsplash.com/photo-1535572290543-960a8046f5af?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Hot Wheels Ultimate Garage',
                'slug' => 'hot-wheels-ultimate-garage',
                'sku' => 'TOY-HOT-001',
                'description' => 'Multi-level race garage with motorized spiral ramp, 90 car capacity, shark chase feature, and 2 Hot Wheels cars included.',
                'price' => 129.99,
                'stock' => 25,
                'category' => 'toys',
                'images' => ['https://images.unsplash.com/photo-1594787317869-82836338e8c2?w=600&auto=format&fit=crop'],
            ],
            // Beauty
            [
                'name' => 'Dyson Airwrap Complete Styler',
                'slug' => 'dyson-airwrap-complete-styler',
                'sku' => 'BEA-DYS-001',
                'description' => 'Multi-styler that curls, waves, smooths, and dries hair simultaneously. Uses Coanda effect instead of extreme heat to protect hair.',
                'price' => 599.99,
                'stock' => 18,
                'category' => 'beauty',
                'images' => ['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'CeraVe Moisturizing Cream',
                'slug' => 'cerave-moisturizing-cream',
                'sku' => 'BEA-CER-001',
                'description' => 'Daily moisturizing cream for dry to very dry skin with essential ceramides, hyaluronic acid, and MVE technology for 24-hour hydration.',
                'price' => 18.99,
                'stock' => 250,
                'category' => 'beauty',
                'images' => ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Charlotte Tilbury Magic Cream',
                'slug' => 'charlotte-tilbury-magic-cream',
                'sku' => 'BEA-CHA-001',
                'description' => 'Luxurious moisturizer with hyaluronic acid, rosehip oil, and vitamins C and E. Plumps, hydrates, and gives skin a lit-from-within glow.',
                'price' => 105.00,
                'stock' => 65,
                'category' => 'beauty',
                'images' => ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Oral-B iO Series 9 Electric Toothbrush',
                'slug' => 'oral-b-io-series-9-electric-toothbrush',
                'sku' => 'BEA-ORA-001',
                'description' => 'Smart electric toothbrush with AI recognition, magnetic charging, pressure sensor, interactive display, and 7 brushing modes.',
                'price' => 219.99,
                'stock' => 45,
                'category' => 'beauty',
                'images' => ['https://images.unsplash.com/photo-1559591937-abc77b0a4f68?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => "L'Oreal Paris Elvive Shampoo",
                'slug' => 'loreal-paris-elvive-shampoo',
                'sku' => 'BEA-LOR-001',
                'description' => 'Extraordinary oil nourishing shampoo with precious flower oils blend for dry, dull hair. Leaves hair silky, shiny, and manageable.',
                'price' => 8.97,
                'stock' => 400,
                'category' => 'beauty',
                'images' => ['https://images.unsplash.com/photo-1585232350483-e3dd00d4e0bc?w=600&auto=format&fit=crop'],
            ],
            // Automotive
            [
                'name' => 'Garmin DriveSmart 65 GPS',
                'slug' => 'garmin-drivesmart-65-gps',
                'sku' => 'AUT-GAR-001',
                'description' => 'Large 6.95-inch GPS navigator with traffic alerts, Alexa built-in, smart notification, driver awareness alerts, and lifetime maps.',
                'price' => 219.99,
                'stock' => 40,
                'category' => 'automotive',
                'images' => ['https://images.unsplash.com/photo-1621963056-4d53e39f91d4?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Thinkware U1000 Dash Cam',
                'slug' => 'thinkware-u1000-dash-cam',
                'sku' => 'AUT-THI-001',
                'description' => '4K front dash cam with built-in GPS, radar and laser detection, ADAS features, cloud connectivity, and Sony STARVIS sensor.',
                'price' => 299.99,
                'stock' => 30,
                'category' => 'automotive',
                'images' => ['https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'NOCO Boost Plus Jump Starter',
                'slug' => 'noco-boost-plus-jump-starter',
                'sku' => 'AUT-NOC-001',
                'description' => 'Portable 1000A peak car jump starter for up to 4-liter gas and 2-liter diesel engines. Also serves as power bank for USB devices.',
                'price' => 99.95,
                'stock' => 55,
                'category' => 'automotive',
                'images' => ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Chemical Guys Car Wash Kit',
                'slug' => 'chemical-guys-car-wash-kit',
                'sku' => 'AUT-CHE-001',
                'description' => 'Complete 14-piece car wash kit including foamy car wash soap, microfiber wash mitt, drying towel, wheel brush, and detailing spray.',
                'price' => 59.99,
                'stock' => 85,
                'category' => 'automotive',
                'images' => ['https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=600&auto=format&fit=crop'],
            ],
            [
                'name' => 'Meguiar\'s Gold Class Car Wax',
                'slug' => 'meguiars-gold-class-car-wax',
                'sku' => 'AUT-MEG-001',
                'description' => 'Premium carnauba-based car wax with advanced conditioning agents that cleans, polishes, and protects paint in one easy step.',
                'price' => 22.99,
                'stock' => 120,
                'category' => 'automotive',
                'images' => ['https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&auto=format&fit=crop'],
            ],
        ];

        foreach ($products as $productData) {
            $category = Category::where('slug', $productData['category'])->first();

            if ($category) {
                Product::create([
                    'name' => $productData['name'],
                    'slug' => $productData['slug'],
                    'sku' => $productData['sku'], 
                    'description' => $productData['description'],
                    'price' => $productData['price'],
                    'stock' => $productData['stock'],
                    'category_id' => $category->id,
                    'images' => $productData['images'],
                ]);
            }
        }
    }
}