services:
  - type: web
    name: laravel-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false 
      - key: APP_URL
        value: https://laravel-api.onrender.com  
      - key: LOG_CHANNEL
        value: stderr  
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ecommerce-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ecommerce-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ecommerce-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: ecommerce-db
    databaseName: laravel
    user: laravel
    plan: free